name: Issues (Cron)
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          close-issue-message: Closed due to inactivity. Please reopen when you get a chance to respond.
          days-before-close: 1
          days-before-stale: 30
          only-labels: 'awaiting response'
          skip-stale-issue-message: true
          skip-stale-pr-message: true
          stale-issue-label: stale
